### ISSUE TITLE
reduced functionality in isolated AP mode

### ISSUE THREAD

**Issue by caveman99** [meshtastic/web#8]
When this interface is used from the actual device, it loads inter.css (a webfont definition) and the mapbox-gl.js from external locations. In AP mode the browser may not have internet connectivity so the parts depending on these Scrips will not work, if said scripts are not already cached. If including them on-device will take up too much space, there need to be safeguards to disable those parts cleanly if missing and not render the application inoperable as a whole.

**Comment by thezolon** [comment]
meshtastic.local (and 192.168.4.1) has a page load timeout when using isolated ip because it is attempting to reach out to these URLs when on an android tablet. If the T-Beam is a wifi client on a network with internet access, everything works.

Meshtastic: 1.2.59
Hardware: T-Beam v1.1
Client Device: Honeywell Android 9 Tablet & Samsung S22 Ultra

**Comment by caveman99** [comment]
AP mode was removed from device firmware.
