### ISSUE TITLE
Web flasher asks twice if you want to update or overwrite

### ISSUE THREAD

**Issue by bmidgley** [meshtastic/web#97]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/63477/222976379-5aa8f228-6e33-4f29-8074-000b4123869a.png">

I appears the web flasher is asking a second time if you want to erase the settings. You choose once in the dropdown and again with this checkbox. But it could be for some other purpose which is confusing.

**Comment by caveman99** [comment]
we're using different flash layouts for erasing or updating. That's what you select with the dropdown. The second prompt is from the flasher itself and can not be disabled that easily, since it's 3rd party code. The Flasher in its currentform is only a makeshift solution till our own integrated flasher in the docs page is fully functional. This problem will be solved when we switch to the new code base.

**Comment by pdxlocations** [comment]
> 
> I appears the web flasher is asking a second time if you want to erase the settings. You choose once in the dropdown and again with this checkbox. But it could be for some other purpose which is confusing.

can this be closed?
