### ISSUE TITLE
Web CLi ADC entries only allow whole numbers

### ISSUE THREAD

**Issue by RightHandMan1** [meshtastic/web#98]
think I found a bug in the WebCLi .. for a Heltec V3,  config, power, ADC will not let me enter anything but whole numbers. The Android app will..

**Comment by sachaw** [comment]
Fixed in 3058dc0185c49538185cfdfa9d9a92e4871d53d4

**Comment by chrisdrackett** [comment]
@sachaw this fix did not work because `Number.parseInt()` is being run on this field which will strip all decimals. Also, the iOS interface supports more than 2 decimal places, so even if `parseFloat` was used it would not be possible to use what I assume are valid values (for example the default for the `lora_isp4520` is `1.436`
